-- SQLite
PRAGMA foreign_keys = ON;

DROP TABLE TB_USER;
CREATE TABLE TB_USER (
    PK_USER INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT,
    EMAIL TEXT,
    IMAGE_URL TEXT
);

DROP TABLE TB_USER_PLATAFORM;
CREATE TABLE TB_USER_PLATAFORM (
    FK_USER INTEGER,
    PLATAFORM TEXT,
    EMAIL TEXT,
    FOREIGN KEY(FK_USER)
        REFERENCES TB_USER (PK_USER)
);